version: '3'
services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:10.5'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
      TZ: Europe/Berlin
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '3306'
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: "keycloak"
    volumes:
      - ./keycloak/opendatenschutzcenter-realm.json:/opt/keycloak/data/import/opendatenschutzcenter-realm.json
    command:
      - --verbose
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: true
      VIRTUAL_HOST: dev-keycloak.mydomain.com
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: dev-keycloak.mydomain.com
      TZ: Europe/Berlin
    ports:
      - '8080:8080'

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###