# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.path.images: /uploads/images/products
    secret: '%env(APP_SECRET)%'
    akademieEmail: '%env(AKADEMIE_EMAIL)%'
    defaultEmail: '%env(DEFAULT_EMAIL)%'
    cronToken: '%env(CRON_TOKEN)%'
    cronIPAdress: '%env(CRON_IPADRESS)%'
    KEYCLOAK_URL: '%env(OAUTH_KEYCLOAK_SERVER)%'
    KEYCLOAK_REALM: '%env(OAUTH_KEYCLOAK_REALM)%'
    KEYCLOAK_SECRET: '%env(OAUTH_KEYCLOAK_CLIENT_SECRET)%'
    KEYCLOAK_ID: '%env(OAUTH_KEYCLOAK_CLIENT_ID)%'
    superAdminRole: '%env(superAdminRole)%'
    group_api_user_id: '%env(default::GROUP_API_USER_ID)%'
    group_api_roles: '%env(default::csv:GROUP_API_ROLES)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\CronService:
        arguments:
            $cronIPAdress: '%cronIPAdress%'
            $cronToken: '%cronToken%'

    app.menu.service:
        class: App\Service\MenuService
        arguments: [ "@knp_menu.factory" ]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createElementsMenu, alias: elements }
            - { name: knp_menu.menu_builder, method: createAcademyMenu, alias: academy }
            - { name: knp_menu.menu_builder, method: createTeamAdminMenu, alias: teamAdmin }
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }

    Gedmo\Tree\TreeListener:
        tags:
            -  name: doctrine.event_subscriber
               connection: default
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    App\Security\KeycloakAuthenticator:
        arguments:
            $groupApiUserId: '%group_api_user_id%'
            $groupApiRoles: '%group_api_roles%'
