<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210111074821 extends AbstractMigration
{
    public function getDescription() : string
    {
        return 'initial migration';
    }

    public function up(Schema $schema) : void
    {
        // only apply if not migrated
        if(!$schema->hasTable('akademie_buchungen')){
            $this->addSql('CREATE TABLE akademie_buchungen (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, kurs_id INT NOT NULL, zugewiesen DATETIME NOT NULL, start DATETIME DEFAULT NULL, ende DATETIME DEFAULT NULL, abgeschlossen TINYINT(1) DEFAULT NULL, vorlage LONGTEXT DEFAULT NULL, buchungs_id LONGTEXT DEFAULT NULL, finished_id LONGTEXT DEFAULT NULL, invitation TINYINT(1) NOT NULL, INDEX IDX_B64F2832A76ED395 (user_id), INDEX IDX_B64F28322CAAFBEC (kurs_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE akademie_kurse (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, created_at DATETIME NOT NULL, video LONGTEXT NOT NULL, title LONGTEXT NOT NULL, beschreibung LONGTEXT NOT NULL, activ TINYINT(1) DEFAULT NULL, type INT NOT NULL, INDEX IDX_D70569A1A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE akademie_kurse_team (akademie_kurse_id INT NOT NULL, team_id INT NOT NULL, INDEX IDX_5A1E49987AAED6D1 (akademie_kurse_id), INDEX IDX_5A1E4998296CD8AE (team_id), PRIMARY KEY(akademie_kurse_id, team_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE audit_tom (id INT AUTO_INCREMENT NOT NULL, team_id INT NOT NULL, status_id INT DEFAULT NULL, previous_id INT DEFAULT NULL, user_id INT NOT NULL, assigned_user_id INT DEFAULT NULL, frage LONGTEXT NOT NULL, bemerkung LONGTEXT NOT NULL, empfehlung LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, nummer LONGTEXT NOT NULL, tom_attribut LONGTEXT DEFAULT NULL, tom_ziel INT DEFAULT NULL, kategorie LONGTEXT NOT NULL, INDEX IDX_401DB23296CD8AE (team_id), INDEX IDX_401DB236BF700BD (status_id), UNIQUE INDEX UNIQ_401DB232DE62210 (previous_id), INDEX IDX_401DB23A76ED395 (user_id), INDEX IDX_401DB23ADF66B1A (assigned_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE audit_tom_audit_tom_ziele (audit_tom_id INT NOT NULL, audit_tom_ziele_id INT NOT NULL, INDEX IDX_C302044C498111CF (audit_tom_id), INDEX IDX_C302044C24B29C5F (audit_tom_ziele_id), PRIMARY KEY(audit_tom_id, audit_tom_ziele_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE audit_tom_audit_tom_abteilung (audit_tom_id INT NOT NULL, audit_tom_abteilung_id INT NOT NULL, INDEX IDX_9C1FDA56498111CF (audit_tom_id), INDEX IDX_9C1FDA5659C698F5 (audit_tom_abteilung_id), PRIMARY KEY(audit_tom_id, audit_tom_abteilung_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE audit_tom_abteilung (id INT AUTO_INCREMENT NOT NULL, team_id INT NOT NULL, name LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, INDEX IDX_A7C0EB17296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE audit_tom_status (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT NOT NULL, color LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE audit_tom_ziele (id INT AUTO_INCREMENT NOT NULL, team_id INT DEFAULT NULL, name LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, INDEX IDX_C37215B8296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE client_comment (id INT AUTO_INCREMENT NOT NULL, client_request_id INT NOT NULL, name LONGTEXT DEFAULT NULL, comment LONGTEXT NOT NULL, created_at DATETIME NOT NULL, internal TINYINT(1) NOT NULL, INDEX IDX_C6491611D22A85E4 (client_request_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE client_request (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, assigned_user_id INT DEFAULT NULL, team_id INT NOT NULL, user_valid_by_id INT DEFAULT NULL, uuid LONGTEXT NOT NULL, title LONGTEXT NOT NULL, description LONGTEXT NOT NULL, item INT NOT NULL, created_at DATETIME NOT NULL, email LONGTEXT NOT NULL, name LONGTEXT NOT NULL, email_valid TINYINT(1) NOT NULL, token LONGTEXT NOT NULL, activ INT NOT NULL, valid_user TINYINT(1) NOT NULL, gdpr TINYINT(1) NOT NULL, notes LONGTEXT DEFAULT NULL, pgp LONGTEXT DEFAULT NULL, password LONGTEXT NOT NULL, open TINYINT(1) NOT NULL, firstname LONGTEXT DEFAULT NULL, lastname LONGTEXT DEFAULT NULL, street LONGTEXT DEFAULT NULL, city LONGTEXT DEFAULT NULL, birthday DATE DEFAULT NULL, INDEX IDX_69AACBE2A76ED395 (user_id), INDEX IDX_69AACBE2ADF66B1A (assigned_user_id), INDEX IDX_69AACBE2296CD8AE (team_id), INDEX IDX_69AACBE27139436A (user_valid_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE datenweitergabe (id INT AUTO_INCREMENT NOT NULL, kontakt_id INT NOT NULL, team_id INT NOT NULL, previous_id INT DEFAULT NULL, stand_id INT NOT NULL, grundlage_id INT NOT NULL, user_id INT NOT NULL, assigned_user_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, gegenstand LONGTEXT NOT NULL, verantwortlich LONGTEXT NOT NULL, vertragsform LONGTEXT NOT NULL, created_at DATETIME NOT NULL, zeichnungsdatum DATE DEFAULT NULL, activ INT NOT NULL, nummer LONGTEXT NOT NULL, art INT NOT NULL, updated_at DATETIME DEFAULT NULL, upload VARCHAR(255) DEFAULT NULL, reference LONGTEXT DEFAULT NULL, approved TINYINT(1) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, check_items TINYINT(1) NOT NULL, check_people TINYINT(1) NOT NULL, check_data TINYINT(1) NOT NULL, check_documentation TINYINT(1) NOT NULL, check_trust TINYINT(1) NOT NULL, check_tom TINYINT(1) NOT NULL, check_subcontractor TINYINT(1) NOT NULL, check_support TINYINT(1) NOT NULL, check_support3236 TINYINT(1) NOT NULL, check_ending TINYINT(1) NOT NULL, check_audit TINYINT(1) NOT NULL, check_notes TINYINT(1) NOT NULL, INDEX IDX_4D6337B7C4062E7F (kontakt_id), INDEX IDX_4D6337B7296CD8AE (team_id), UNIQUE INDEX UNIQ_4D6337B72DE62210 (previous_id), INDEX IDX_4D6337B79734D487 (stand_id), INDEX IDX_4D6337B760655851 (grundlage_id), INDEX IDX_4D6337B7A76ED395 (user_id), INDEX IDX_4D6337B7ADF66B1A (assigned_user_id), INDEX IDX_4D6337B72D234F6A (approved_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE datenweitergabe_grundlagen (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE datenweitergabe_stand (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT NOT NULL, network TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE forms (id INT AUTO_INCREMENT NOT NULL, team_id INT NOT NULL, user_id INT NOT NULL, previous_id INT DEFAULT NULL, assigned_user_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, updated_at DATETIME DEFAULT NULL, upload VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, title LONGTEXT NOT NULL, version LONGTEXT NOT NULL, activ INT NOT NULL, description LONGTEXT DEFAULT NULL, status INT NOT NULL, approved TINYINT(1) DEFAULT NULL, INDEX IDX_FD3F1BF7296CD8AE (team_id), INDEX IDX_FD3F1BF7A76ED395 (user_id), UNIQUE INDEX UNIQ_FD3F1BF72DE62210 (previous_id), INDEX IDX_FD3F1BF7ADF66B1A (assigned_user_id), INDEX IDX_FD3F1BF72D234F6A (approved_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE forms_produkte (forms_id INT NOT NULL, produkte_id INT NOT NULL, INDEX IDX_43DCA781C99A463F (forms_id), INDEX IDX_43DCA781F5AB0B87 (produkte_id), PRIMARY KEY(forms_id, produkte_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE forms_audit_tom_abteilung (forms_id INT NOT NULL, audit_tom_abteilung_id INT NOT NULL, INDEX IDX_6E62398FC99A463F (forms_id), INDEX IDX_6E62398F59C698F5 (audit_tom_abteilung_id), PRIMARY KEY(forms_id, audit_tom_abteilung_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE fos_user (id INT AUTO_INCREMENT NOT NULL, team_id INT DEFAULT NULL, akademie_user_id INT DEFAULT NULL, admin_user_id INT DEFAULT NULL, email LONGTEXT NOT NULL, keycloak_id LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL, username LONGTEXT DEFAULT NULL, last_login DATETIME DEFAULT NULL, first_name LONGTEXT DEFAULT NULL, last_name LONGTEXT DEFAULT NULL, register_id LONGTEXT DEFAULT NULL, INDEX IDX_957A6479296CD8AE (team_id), INDEX IDX_957A64799E73AC3E (akademie_user_id), INDEX IDX_957A64796352511C (admin_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE kontakte (id INT AUTO_INCREMENT NOT NULL, team_id INT NOT NULL, approved_by_id INT DEFAULT NULL, firma LONGTEXT DEFAULT NULL, anrede LONGTEXT DEFAULT NULL, vorname LONGTEXT DEFAULT NULL, nachname LONGTEXT DEFAULT NULL, strase LONGTEXT NOT NULL, plz LONGTEXT NOT NULL, ort LONGTEXT NOT NULL, email LONGTEXT DEFAULT NULL, telefon LONGTEXT DEFAULT NULL, bemerkung LONGTEXT DEFAULT NULL, art INT NOT NULL, activ INT NOT NULL, nummer LONGTEXT DEFAULT NULL, approved TINYINT(1) DEFAULT NULL, INDEX IDX_1A62EA2F296CD8AE (team_id), INDEX IDX_1A62EA2F2D234F6A (approved_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE policies (id INT AUTO_INCREMENT NOT NULL, team_id INT NOT NULL, user_id INT NOT NULL, previous_id INT DEFAULT NULL, person_id INT NOT NULL, assigned_user_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, created_at DATETIME NOT NULL, activ INT NOT NULL, scope LONGTEXT NOT NULL, risk LONGTEXT NOT NULL, foundation LONGTEXT NOT NULL, protection LONGTEXT NOT NULL, notes LONGTEXT DEFAULT NULL, consequences LONGTEXT DEFAULT NULL, contact LONGTEXT DEFAULT NULL, status INT NOT NULL, title LONGTEXT NOT NULL, reference LONGTEXT DEFAULT NULL, upload VARCHAR(255) DEFAULT NULL, approved TINYINT(1) DEFAULT NULL, INDEX IDX_E08BBFCE296CD8AE (team_id), INDEX IDX_E08BBFCEA76ED395 (user_id), UNIQUE INDEX UNIQ_E08BBFCE2DE62210 (previous_id), INDEX IDX_E08BBFCE217BBB47 (person_id), INDEX IDX_E08BBFCEADF66B1A (assigned_user_id), INDEX IDX_E08BBFCE2D234F6A (approved_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE policies_vvt (policies_id INT NOT NULL, vvt_id INT NOT NULL, INDEX IDX_ECB63CBFE4479645 (policies_id), INDEX IDX_ECB63CBF677671F9 (vvt_id), PRIMARY KEY(policies_id, vvt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE policies_vvtpersonen (policies_id INT NOT NULL, vvtpersonen_id INT NOT NULL, INDEX IDX_3A4A1837E4479645 (policies_id), INDEX IDX_3A4A183797064E08 (vvtpersonen_id), PRIMARY KEY(policies_id, vvtpersonen_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE policies_vvtdatenkategorie (policies_id INT NOT NULL, vvtdatenkategorie_id INT NOT NULL, INDEX IDX_1FEC288EE4479645 (policies_id), INDEX IDX_1FEC288E45450705 (vvtdatenkategorie_id), PRIMARY KEY(policies_id, vvtdatenkategorie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE produkte (id INT AUTO_INCREMENT NOT NULL, team_id INT NOT NULL, name LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, INDEX IDX_497DBEB3296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE report (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, team_id INT NOT NULL, date DATE NOT NULL, start TIME NOT NULL, end TIME NOT NULL, calc_time DOUBLE PRECISION NOT NULL, description LONGTEXT NOT NULL, invoice TINYINT(1) DEFAULT NULL, onsite TINYINT(1) DEFAULT NULL, in_report TINYINT(1) DEFAULT NULL, activ INT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_C42F7784A76ED395 (user_id), INDEX IDX_C42F7784296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE software (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, team_id INT NOT NULL, previous_id INT DEFAULT NULL, assigned_user_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, name LONGTEXT NOT NULL, build LONGTEXT NOT NULL, purchase DATE NOT NULL, activ TINYINT(1) NOT NULL, license LONGTEXT DEFAULT NULL, license_expiration DATE DEFAULT NULL, description LONGTEXT NOT NULL, status INT DEFAULT NULL, created_at DATETIME NOT NULL, location LONGTEXT DEFAULT NULL, nummer LONGTEXT DEFAULT NULL, reference LONGTEXT DEFAULT NULL, approved TINYINT(1) DEFAULT NULL, archiving LONGTEXT DEFAULT NULL, recovery LONGTEXT DEFAULT NULL, permissions LONGTEXT DEFAULT NULL, license_type INT NOT NULL, INDEX IDX_77D068CFA76ED395 (user_id), INDEX IDX_77D068CF296CD8AE (team_id), UNIQUE INDEX UNIQ_77D068CF2DE62210 (previous_id), INDEX IDX_77D068CFADF66B1A (assigned_user_id), INDEX IDX_77D068CF2D234F6A (approved_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE software_vvt (software_id INT NOT NULL, vvt_id INT NOT NULL, INDEX IDX_EBE8FA17D7452741 (software_id), INDEX IDX_EBE8FA17677671F9 (vvt_id), PRIMARY KEY(software_id, vvt_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE software_datenweitergabe (software_id INT NOT NULL, datenweitergabe_id INT NOT NULL, INDEX IDX_22997BA8D7452741 (software_id), INDEX IDX_22997BA8E2ECBD3E (datenweitergabe_id), PRIMARY KEY(software_id, datenweitergabe_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE software_config (id INT AUTO_INCREMENT NOT NULL, software_id INT NOT NULL, name LONGTEXT NOT NULL, config LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, upload VARCHAR(255) DEFAULT NULL, INDEX IDX_8C564DD6D7452741 (software_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE task (id INT AUTO_INCREMENT NOT NULL, assigned_user_id INT DEFAULT NULL, team_id INT DEFAULT NULL, user_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, activ INT NOT NULL, created_at DATETIME NOT NULL, task LONGTEXT NOT NULL, done TINYINT(1) NOT NULL, title LONGTEXT NOT NULL, end_date DATE DEFAULT NULL, prio INT NOT NULL, done_date DATE DEFAULT NULL, INDEX IDX_527EDB25ADF66B1A (assigned_user_id), INDEX IDX_527EDB25296CD8AE (team_id), INDEX IDX_527EDB25A76ED395 (user_id), INDEX IDX_527EDB25896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE team (id INT AUTO_INCREMENT NOT NULL, dsb_user_id INT DEFAULT NULL, name LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, strasse LONGTEXT NOT NULL, plz LONGTEXT NOT NULL, stadt LONGTEXT NOT NULL, email LONGTEXT DEFAULT NULL, telefon LONGTEXT DEFAULT NULL, dsb LONGTEXT DEFAULT NULL, ceo LONGTEXT NOT NULL, cloned_at DATETIME DEFAULT NULL, signature LONGTEXT DEFAULT NULL, external_link LONGTEXT DEFAULT NULL, video LONGTEXT DEFAULT NULL, slug LONGTEXT DEFAULT NULL, industry LONGTEXT DEFAULT NULL, specialty LONGTEXT DEFAULT NULL, INDEX IDX_C4E0A61F52652E6E (dsb_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE tom (id INT AUTO_INCREMENT NOT NULL, team_id INT NOT NULL, user_id INT NOT NULL, previous_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, created_at DATETIME NOT NULL, activ INT NOT NULL, tom_pseudo LONGTEXT NOT NULL, tom_zutrittskontrolle LONGTEXT NOT NULL, tom_zugangskontrolle LONGTEXT NOT NULL, tom_zugriffskontrolle LONGTEXT NOT NULL, tom_benutzerkontrolle LONGTEXT NOT NULL, tom_speicherkontrolle LONGTEXT NOT NULL, tom_trennbarkeit LONGTEXT NOT NULL, tom_datenintegritaet LONGTEXT NOT NULL, tom_transportkontrolle LONGTEXT NOT NULL, tom_uebertragungskontrolle LONGTEXT NOT NULL, tom_zuverlaessigkeit LONGTEXT NOT NULL, tom_auftragskontrolle LONGTEXT NOT NULL, tom_verfuegbarkeitskontrolle LONGTEXT NOT NULL, tom_wiederherstellbarkeit LONGTEXT NOT NULL, tom_audit LONGTEXT NOT NULL, tom_eingabekontrolle LONGTEXT NOT NULL, beschreibung LONGTEXT NOT NULL, titel LONGTEXT NOT NULL, approved TINYINT(1) DEFAULT NULL, INDEX IDX_7DDF7313296CD8AE (team_id), INDEX IDX_7DDF7313A76ED395 (user_id), UNIQUE INDEX UNIQ_7DDF73132DE62210 (previous_id), INDEX IDX_7DDF73132D234F6A (approved_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE upload (id INT AUTO_INCREMENT NOT NULL, file VARCHAR(255) DEFAULT NULL, updated_at DATETIME NOT NULL, uid VARCHAR(50) NOT NULL, amount INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vorfall (id INT AUTO_INCREMENT NOT NULL, team_id INT NOT NULL, user_id INT NOT NULL, previous_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, assigned_user_id INT DEFAULT NULL, fakten LONGTEXT NOT NULL, auswirkung LONGTEXT NOT NULL, massnahmen LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, datum DATETIME NOT NULL, gemeldet TINYINT(1) NOT NULL, nummer LONGTEXT NOT NULL, betroffene_gemeldet TINYINT(1) NOT NULL, auftraggeber_gemeldet TINYINT(1) NOT NULL, approved TINYINT(1) DEFAULT NULL, INDEX IDX_B270345F296CD8AE (team_id), INDEX IDX_B270345FA76ED395 (user_id), UNIQUE INDEX UNIQ_B270345F2DE62210 (previous_id), INDEX IDX_B270345F2D234F6A (approved_by_id), INDEX IDX_B270345FADF66B1A (assigned_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vorfall_vvtpersonen (vorfall_id INT NOT NULL, vvtpersonen_id INT NOT NULL, INDEX IDX_2DF87A01EA8E2EC4 (vorfall_id), INDEX IDX_2DF87A0197064E08 (vvtpersonen_id), PRIMARY KEY(vorfall_id, vvtpersonen_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vorfall_vvtdatenkategorie (vorfall_id INT NOT NULL, vvtdatenkategorie_id INT NOT NULL, INDEX IDX_802FDBF7EA8E2EC4 (vorfall_id), INDEX IDX_802FDBF745450705 (vvtdatenkategorie_id), PRIMARY KEY(vorfall_id, vvtdatenkategorie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvt (id INT AUTO_INCREMENT NOT NULL, status_id INT NOT NULL, team_id INT NOT NULL, previous_id INT DEFAULT NULL, user_id INT NOT NULL, user_contract_id INT NOT NULL, tom_link_id INT DEFAULT NULL, abteilung_id INT DEFAULT NULL, assigned_user_id INT DEFAULT NULL, approved_by_id INT DEFAULT NULL, name LONGTEXT NOT NULL, verantwortlich LONGTEXT DEFAULT NULL, zweck LONGTEXT NOT NULL, joint_control TINYINT(1) NOT NULL, auftragsverarbeitung TINYINT(1) NOT NULL, speicherung LONGTEXT DEFAULT NULL, weitergabe LONGTEXT DEFAULT NULL, eu TINYINT(1) NOT NULL, loeschfrist LONGTEXT NOT NULL, tom LONGTEXT DEFAULT NULL, nummer LONGTEXT NOT NULL, activ INT NOT NULL, created_at DATETIME NOT NULL, informationspflicht LONGTEXT DEFAULT NULL, dsb LONGTEXT DEFAULT NULL, beurteilung_eintritt INT NOT NULL, beurteilung_schaden INT NOT NULL, approved TINYINT(1) DEFAULT NULL, source LONGTEXT DEFAULT NULL, INDEX IDX_8130A6A56BF700BD (status_id), INDEX IDX_8130A6A5296CD8AE (team_id), UNIQUE INDEX UNIQ_8130A6A52DE62210 (previous_id), INDEX IDX_8130A6A5A76ED395 (user_id), INDEX IDX_8130A6A58C6D2968 (user_contract_id), INDEX IDX_8130A6A5147295F6 (tom_link_id), INDEX IDX_8130A6A5E862333F (abteilung_id), INDEX IDX_8130A6A5ADF66B1A (assigned_user_id), INDEX IDX_8130A6A52D234F6A (approved_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvt_vvtgrundlage (vvt_id INT NOT NULL, vvtgrundlage_id INT NOT NULL, INDEX IDX_A27B631A677671F9 (vvt_id), INDEX IDX_A27B631A80257D66 (vvtgrundlage_id), PRIMARY KEY(vvt_id, vvtgrundlage_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvt_vvtpersonen (vvt_id INT NOT NULL, vvtpersonen_id INT NOT NULL, INDEX IDX_8B3FCF56677671F9 (vvt_id), INDEX IDX_8B3FCF5697064E08 (vvtpersonen_id), PRIMARY KEY(vvt_id, vvtpersonen_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvt_vvtdatenkategorie (vvt_id INT NOT NULL, vvtdatenkategorie_id INT NOT NULL, INDEX IDX_7FEC93B1677671F9 (vvt_id), INDEX IDX_7FEC93B145450705 (vvtdatenkategorie_id), PRIMARY KEY(vvt_id, vvtdatenkategorie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvt_vvtrisiken (vvt_id INT NOT NULL, vvtrisiken_id INT NOT NULL, INDEX IDX_1FAB2B94677671F9 (vvt_id), INDEX IDX_1FAB2B94DF7C8617 (vvtrisiken_id), PRIMARY KEY(vvt_id, vvtrisiken_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvt_datenweitergabe (vvt_id INT NOT NULL, datenweitergabe_id INT NOT NULL, INDEX IDX_33B13935677671F9 (vvt_id), INDEX IDX_33B13935E2ECBD3E (datenweitergabe_id), PRIMARY KEY(vvt_id, datenweitergabe_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvt_produkte (vvt_id INT NOT NULL, produkte_id INT NOT NULL, INDEX IDX_D823B054677671F9 (vvt_id), INDEX IDX_D823B054F5AB0B87 (produkte_id), PRIMARY KEY(vvt_id, produkte_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvtdatenkategorie (id INT AUTO_INCREMENT NOT NULL, team_id INT DEFAULT NULL, name LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, INDEX IDX_91E13AAD296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvtdsfa (id INT AUTO_INCREMENT NOT NULL, previous_id INT DEFAULT NULL, vvt_id INT NOT NULL, user_id INT NOT NULL, assigned_user_id INT DEFAULT NULL, beschreibung LONGTEXT NOT NULL, notwendigkeit LONGTEXT NOT NULL, risiko LONGTEXT NOT NULL, abhilfe LONGTEXT NOT NULL, standpunkt LONGTEXT NOT NULL, dsb LONGTEXT DEFAULT NULL, ergebnis LONGTEXT DEFAULT NULL, activ TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_281CB90E2DE62210 (previous_id), INDEX IDX_281CB90E677671F9 (vvt_id), INDEX IDX_281CB90EA76ED395 (user_id), INDEX IDX_281CB90EADF66B1A (assigned_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvtgrundlage (id INT AUTO_INCREMENT NOT NULL, team_id INT DEFAULT NULL, name LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, INDEX IDX_407DE499296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvtpersonen (id INT AUTO_INCREMENT NOT NULL, team_id INT DEFAULT NULL, name LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, INDEX IDX_35C2589F296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvtrisiken (id INT AUTO_INCREMENT NOT NULL, team_id INT DEFAULT NULL, name LONGTEXT NOT NULL, activ TINYINT(1) NOT NULL, INDEX IDX_E92CF2E6296CD8AE (team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE vvtstatus (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT NOT NULL, color LONGTEXT DEFAULT NULL, network TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
            $this->addSql('ALTER TABLE akademie_buchungen ADD CONSTRAINT FK_B64F2832A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE akademie_buchungen ADD CONSTRAINT FK_B64F28322CAAFBEC FOREIGN KEY (kurs_id) REFERENCES akademie_kurse (id)');
            $this->addSql('ALTER TABLE akademie_kurse ADD CONSTRAINT FK_D70569A1A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE akademie_kurse_team ADD CONSTRAINT FK_5A1E49987AAED6D1 FOREIGN KEY (akademie_kurse_id) REFERENCES akademie_kurse (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE akademie_kurse_team ADD CONSTRAINT FK_5A1E4998296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE audit_tom ADD CONSTRAINT FK_401DB23296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE audit_tom ADD CONSTRAINT FK_401DB236BF700BD FOREIGN KEY (status_id) REFERENCES audit_tom_status (id)');
            $this->addSql('ALTER TABLE audit_tom ADD CONSTRAINT FK_401DB232DE62210 FOREIGN KEY (previous_id) REFERENCES audit_tom (id)');
            $this->addSql('ALTER TABLE audit_tom ADD CONSTRAINT FK_401DB23A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE audit_tom ADD CONSTRAINT FK_401DB23ADF66B1A FOREIGN KEY (assigned_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE audit_tom_audit_tom_ziele ADD CONSTRAINT FK_C302044C498111CF FOREIGN KEY (audit_tom_id) REFERENCES audit_tom (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE audit_tom_audit_tom_ziele ADD CONSTRAINT FK_C302044C24B29C5F FOREIGN KEY (audit_tom_ziele_id) REFERENCES audit_tom_ziele (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE audit_tom_audit_tom_abteilung ADD CONSTRAINT FK_9C1FDA56498111CF FOREIGN KEY (audit_tom_id) REFERENCES audit_tom (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE audit_tom_audit_tom_abteilung ADD CONSTRAINT FK_9C1FDA5659C698F5 FOREIGN KEY (audit_tom_abteilung_id) REFERENCES audit_tom_abteilung (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE audit_tom_abteilung ADD CONSTRAINT FK_A7C0EB17296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE audit_tom_ziele ADD CONSTRAINT FK_C37215B8296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE client_comment ADD CONSTRAINT FK_C6491611D22A85E4 FOREIGN KEY (client_request_id) REFERENCES client_request (id)');
            $this->addSql('ALTER TABLE client_request ADD CONSTRAINT FK_69AACBE2A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE client_request ADD CONSTRAINT FK_69AACBE2ADF66B1A FOREIGN KEY (assigned_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE client_request ADD CONSTRAINT FK_69AACBE2296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE client_request ADD CONSTRAINT FK_69AACBE27139436A FOREIGN KEY (user_valid_by_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE datenweitergabe ADD CONSTRAINT FK_4D6337B7C4062E7F FOREIGN KEY (kontakt_id) REFERENCES kontakte (id)');
            $this->addSql('ALTER TABLE datenweitergabe ADD CONSTRAINT FK_4D6337B7296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE datenweitergabe ADD CONSTRAINT FK_4D6337B72DE62210 FOREIGN KEY (previous_id) REFERENCES datenweitergabe (id)');
            $this->addSql('ALTER TABLE datenweitergabe ADD CONSTRAINT FK_4D6337B79734D487 FOREIGN KEY (stand_id) REFERENCES datenweitergabe_stand (id)');
            $this->addSql('ALTER TABLE datenweitergabe ADD CONSTRAINT FK_4D6337B760655851 FOREIGN KEY (grundlage_id) REFERENCES datenweitergabe_grundlagen (id)');
            $this->addSql('ALTER TABLE datenweitergabe ADD CONSTRAINT FK_4D6337B7A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE datenweitergabe ADD CONSTRAINT FK_4D6337B7ADF66B1A FOREIGN KEY (assigned_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE datenweitergabe ADD CONSTRAINT FK_4D6337B72D234F6A FOREIGN KEY (approved_by_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE forms ADD CONSTRAINT FK_FD3F1BF7296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE forms ADD CONSTRAINT FK_FD3F1BF7A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE forms ADD CONSTRAINT FK_FD3F1BF72DE62210 FOREIGN KEY (previous_id) REFERENCES forms (id)');
            $this->addSql('ALTER TABLE forms ADD CONSTRAINT FK_FD3F1BF7ADF66B1A FOREIGN KEY (assigned_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE forms ADD CONSTRAINT FK_FD3F1BF72D234F6A FOREIGN KEY (approved_by_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE forms_produkte ADD CONSTRAINT FK_43DCA781C99A463F FOREIGN KEY (forms_id) REFERENCES forms (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE forms_produkte ADD CONSTRAINT FK_43DCA781F5AB0B87 FOREIGN KEY (produkte_id) REFERENCES produkte (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE forms_audit_tom_abteilung ADD CONSTRAINT FK_6E62398FC99A463F FOREIGN KEY (forms_id) REFERENCES forms (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE forms_audit_tom_abteilung ADD CONSTRAINT FK_6E62398F59C698F5 FOREIGN KEY (audit_tom_abteilung_id) REFERENCES audit_tom_abteilung (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE fos_user ADD CONSTRAINT FK_957A6479296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE fos_user ADD CONSTRAINT FK_957A64799E73AC3E FOREIGN KEY (akademie_user_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE fos_user ADD CONSTRAINT FK_957A64796352511C FOREIGN KEY (admin_user_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE kontakte ADD CONSTRAINT FK_1A62EA2F296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE kontakte ADD CONSTRAINT FK_1A62EA2F2D234F6A FOREIGN KEY (approved_by_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE policies ADD CONSTRAINT FK_E08BBFCE296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE policies ADD CONSTRAINT FK_E08BBFCEA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE policies ADD CONSTRAINT FK_E08BBFCE2DE62210 FOREIGN KEY (previous_id) REFERENCES policies (id)');
            $this->addSql('ALTER TABLE policies ADD CONSTRAINT FK_E08BBFCE217BBB47 FOREIGN KEY (person_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE policies ADD CONSTRAINT FK_E08BBFCEADF66B1A FOREIGN KEY (assigned_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE policies ADD CONSTRAINT FK_E08BBFCE2D234F6A FOREIGN KEY (approved_by_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE policies_vvt ADD CONSTRAINT FK_ECB63CBFE4479645 FOREIGN KEY (policies_id) REFERENCES policies (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE policies_vvt ADD CONSTRAINT FK_ECB63CBF677671F9 FOREIGN KEY (vvt_id) REFERENCES vvt (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE policies_vvtpersonen ADD CONSTRAINT FK_3A4A1837E4479645 FOREIGN KEY (policies_id) REFERENCES policies (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE policies_vvtpersonen ADD CONSTRAINT FK_3A4A183797064E08 FOREIGN KEY (vvtpersonen_id) REFERENCES vvtpersonen (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE policies_vvtdatenkategorie ADD CONSTRAINT FK_1FEC288EE4479645 FOREIGN KEY (policies_id) REFERENCES policies (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE policies_vvtdatenkategorie ADD CONSTRAINT FK_1FEC288E45450705 FOREIGN KEY (vvtdatenkategorie_id) REFERENCES vvtdatenkategorie (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE produkte ADD CONSTRAINT FK_497DBEB3296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE software ADD CONSTRAINT FK_77D068CFA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE software ADD CONSTRAINT FK_77D068CF296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE software ADD CONSTRAINT FK_77D068CF2DE62210 FOREIGN KEY (previous_id) REFERENCES software (id)');
            $this->addSql('ALTER TABLE software ADD CONSTRAINT FK_77D068CFADF66B1A FOREIGN KEY (assigned_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE software ADD CONSTRAINT FK_77D068CF2D234F6A FOREIGN KEY (approved_by_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE software_vvt ADD CONSTRAINT FK_EBE8FA17D7452741 FOREIGN KEY (software_id) REFERENCES software (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE software_vvt ADD CONSTRAINT FK_EBE8FA17677671F9 FOREIGN KEY (vvt_id) REFERENCES vvt (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE software_datenweitergabe ADD CONSTRAINT FK_22997BA8D7452741 FOREIGN KEY (software_id) REFERENCES software (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE software_datenweitergabe ADD CONSTRAINT FK_22997BA8E2ECBD3E FOREIGN KEY (datenweitergabe_id) REFERENCES datenweitergabe (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE software_config ADD CONSTRAINT FK_8C564DD6D7452741 FOREIGN KEY (software_id) REFERENCES software (id)');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25ADF66B1A FOREIGN KEY (assigned_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25896DBBDE FOREIGN KEY (updated_by_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F52652E6E FOREIGN KEY (dsb_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE tom ADD CONSTRAINT FK_7DDF7313296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE tom ADD CONSTRAINT FK_7DDF7313A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE tom ADD CONSTRAINT FK_7DDF73132DE62210 FOREIGN KEY (previous_id) REFERENCES tom (id)');
            $this->addSql('ALTER TABLE tom ADD CONSTRAINT FK_7DDF73132D234F6A FOREIGN KEY (approved_by_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE vorfall ADD CONSTRAINT FK_B270345F296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE vorfall ADD CONSTRAINT FK_B270345FA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE vorfall ADD CONSTRAINT FK_B270345F2DE62210 FOREIGN KEY (previous_id) REFERENCES vorfall (id)');
            $this->addSql('ALTER TABLE vorfall ADD CONSTRAINT FK_B270345F2D234F6A FOREIGN KEY (approved_by_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE vorfall ADD CONSTRAINT FK_B270345FADF66B1A FOREIGN KEY (assigned_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE vorfall_vvtpersonen ADD CONSTRAINT FK_2DF87A01EA8E2EC4 FOREIGN KEY (vorfall_id) REFERENCES vorfall (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vorfall_vvtpersonen ADD CONSTRAINT FK_2DF87A0197064E08 FOREIGN KEY (vvtpersonen_id) REFERENCES vvtpersonen (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vorfall_vvtdatenkategorie ADD CONSTRAINT FK_802FDBF7EA8E2EC4 FOREIGN KEY (vorfall_id) REFERENCES vorfall (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vorfall_vvtdatenkategorie ADD CONSTRAINT FK_802FDBF745450705 FOREIGN KEY (vvtdatenkategorie_id) REFERENCES vvtdatenkategorie (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt ADD CONSTRAINT FK_8130A6A56BF700BD FOREIGN KEY (status_id) REFERENCES vvtstatus (id)');
            $this->addSql('ALTER TABLE vvt ADD CONSTRAINT FK_8130A6A5296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE vvt ADD CONSTRAINT FK_8130A6A52DE62210 FOREIGN KEY (previous_id) REFERENCES vvt (id)');
            $this->addSql('ALTER TABLE vvt ADD CONSTRAINT FK_8130A6A5A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE vvt ADD CONSTRAINT FK_8130A6A58C6D2968 FOREIGN KEY (user_contract_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE vvt ADD CONSTRAINT FK_8130A6A5147295F6 FOREIGN KEY (tom_link_id) REFERENCES tom (id)');
            $this->addSql('ALTER TABLE vvt ADD CONSTRAINT FK_8130A6A5E862333F FOREIGN KEY (abteilung_id) REFERENCES audit_tom_abteilung (id)');
            $this->addSql('ALTER TABLE vvt ADD CONSTRAINT FK_8130A6A5ADF66B1A FOREIGN KEY (assigned_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE vvt ADD CONSTRAINT FK_8130A6A52D234F6A FOREIGN KEY (approved_by_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE vvt_vvtgrundlage ADD CONSTRAINT FK_A27B631A677671F9 FOREIGN KEY (vvt_id) REFERENCES vvt (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_vvtgrundlage ADD CONSTRAINT FK_A27B631A80257D66 FOREIGN KEY (vvtgrundlage_id) REFERENCES vvtgrundlage (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_vvtpersonen ADD CONSTRAINT FK_8B3FCF56677671F9 FOREIGN KEY (vvt_id) REFERENCES vvt (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_vvtpersonen ADD CONSTRAINT FK_8B3FCF5697064E08 FOREIGN KEY (vvtpersonen_id) REFERENCES vvtpersonen (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_vvtdatenkategorie ADD CONSTRAINT FK_7FEC93B1677671F9 FOREIGN KEY (vvt_id) REFERENCES vvt (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_vvtdatenkategorie ADD CONSTRAINT FK_7FEC93B145450705 FOREIGN KEY (vvtdatenkategorie_id) REFERENCES vvtdatenkategorie (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_vvtrisiken ADD CONSTRAINT FK_1FAB2B94677671F9 FOREIGN KEY (vvt_id) REFERENCES vvt (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_vvtrisiken ADD CONSTRAINT FK_1FAB2B94DF7C8617 FOREIGN KEY (vvtrisiken_id) REFERENCES vvtrisiken (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_datenweitergabe ADD CONSTRAINT FK_33B13935677671F9 FOREIGN KEY (vvt_id) REFERENCES vvt (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_datenweitergabe ADD CONSTRAINT FK_33B13935E2ECBD3E FOREIGN KEY (datenweitergabe_id) REFERENCES datenweitergabe (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_produkte ADD CONSTRAINT FK_D823B054677671F9 FOREIGN KEY (vvt_id) REFERENCES vvt (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvt_produkte ADD CONSTRAINT FK_D823B054F5AB0B87 FOREIGN KEY (produkte_id) REFERENCES produkte (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE vvtdatenkategorie ADD CONSTRAINT FK_91E13AAD296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE vvtdsfa ADD CONSTRAINT FK_281CB90E2DE62210 FOREIGN KEY (previous_id) REFERENCES vvtdsfa (id)');
            $this->addSql('ALTER TABLE vvtdsfa ADD CONSTRAINT FK_281CB90E677671F9 FOREIGN KEY (vvt_id) REFERENCES vvt (id)');
            $this->addSql('ALTER TABLE vvtdsfa ADD CONSTRAINT FK_281CB90EA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE vvtdsfa ADD CONSTRAINT FK_281CB90EADF66B1A FOREIGN KEY (assigned_user_id) REFERENCES fos_user (id)');
            $this->addSql('ALTER TABLE vvtgrundlage ADD CONSTRAINT FK_407DE499296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE vvtpersonen ADD CONSTRAINT FK_35C2589F296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
            $this->addSql('ALTER TABLE vvtrisiken ADD CONSTRAINT FK_E92CF2E6296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
        }
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE akademie_buchungen DROP FOREIGN KEY FK_B64F28322CAAFBEC');
        $this->addSql('ALTER TABLE akademie_kurse_team DROP FOREIGN KEY FK_5A1E49987AAED6D1');
        $this->addSql('ALTER TABLE audit_tom DROP FOREIGN KEY FK_401DB232DE62210');
        $this->addSql('ALTER TABLE audit_tom_audit_tom_ziele DROP FOREIGN KEY FK_C302044C498111CF');
        $this->addSql('ALTER TABLE audit_tom_audit_tom_abteilung DROP FOREIGN KEY FK_9C1FDA56498111CF');
        $this->addSql('ALTER TABLE audit_tom_audit_tom_abteilung DROP FOREIGN KEY FK_9C1FDA5659C698F5');
        $this->addSql('ALTER TABLE forms_audit_tom_abteilung DROP FOREIGN KEY FK_6E62398F59C698F5');
        $this->addSql('ALTER TABLE vvt DROP FOREIGN KEY FK_8130A6A5E862333F');
        $this->addSql('ALTER TABLE audit_tom DROP FOREIGN KEY FK_401DB236BF700BD');
        $this->addSql('ALTER TABLE audit_tom_audit_tom_ziele DROP FOREIGN KEY FK_C302044C24B29C5F');
        $this->addSql('ALTER TABLE client_comment DROP FOREIGN KEY FK_C6491611D22A85E4');
        $this->addSql('ALTER TABLE datenweitergabe DROP FOREIGN KEY FK_4D6337B72DE62210');
        $this->addSql('ALTER TABLE software_datenweitergabe DROP FOREIGN KEY FK_22997BA8E2ECBD3E');
        $this->addSql('ALTER TABLE vvt_datenweitergabe DROP FOREIGN KEY FK_33B13935E2ECBD3E');
        $this->addSql('ALTER TABLE datenweitergabe DROP FOREIGN KEY FK_4D6337B760655851');
        $this->addSql('ALTER TABLE datenweitergabe DROP FOREIGN KEY FK_4D6337B79734D487');
        $this->addSql('ALTER TABLE forms DROP FOREIGN KEY FK_FD3F1BF72DE62210');
        $this->addSql('ALTER TABLE forms_produkte DROP FOREIGN KEY FK_43DCA781C99A463F');
        $this->addSql('ALTER TABLE forms_audit_tom_abteilung DROP FOREIGN KEY FK_6E62398FC99A463F');
        $this->addSql('ALTER TABLE akademie_buchungen DROP FOREIGN KEY FK_B64F2832A76ED395');
        $this->addSql('ALTER TABLE akademie_kurse DROP FOREIGN KEY FK_D70569A1A76ED395');
        $this->addSql('ALTER TABLE audit_tom DROP FOREIGN KEY FK_401DB23A76ED395');
        $this->addSql('ALTER TABLE audit_tom DROP FOREIGN KEY FK_401DB23ADF66B1A');
        $this->addSql('ALTER TABLE client_request DROP FOREIGN KEY FK_69AACBE2A76ED395');
        $this->addSql('ALTER TABLE client_request DROP FOREIGN KEY FK_69AACBE2ADF66B1A');
        $this->addSql('ALTER TABLE client_request DROP FOREIGN KEY FK_69AACBE27139436A');
        $this->addSql('ALTER TABLE datenweitergabe DROP FOREIGN KEY FK_4D6337B7A76ED395');
        $this->addSql('ALTER TABLE datenweitergabe DROP FOREIGN KEY FK_4D6337B7ADF66B1A');
        $this->addSql('ALTER TABLE datenweitergabe DROP FOREIGN KEY FK_4D6337B72D234F6A');
        $this->addSql('ALTER TABLE forms DROP FOREIGN KEY FK_FD3F1BF7A76ED395');
        $this->addSql('ALTER TABLE forms DROP FOREIGN KEY FK_FD3F1BF7ADF66B1A');
        $this->addSql('ALTER TABLE forms DROP FOREIGN KEY FK_FD3F1BF72D234F6A');
        $this->addSql('ALTER TABLE kontakte DROP FOREIGN KEY FK_1A62EA2F2D234F6A');
        $this->addSql('ALTER TABLE policies DROP FOREIGN KEY FK_E08BBFCEA76ED395');
        $this->addSql('ALTER TABLE policies DROP FOREIGN KEY FK_E08BBFCE217BBB47');
        $this->addSql('ALTER TABLE policies DROP FOREIGN KEY FK_E08BBFCEADF66B1A');
        $this->addSql('ALTER TABLE policies DROP FOREIGN KEY FK_E08BBFCE2D234F6A');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784A76ED395');
        $this->addSql('ALTER TABLE software DROP FOREIGN KEY FK_77D068CFA76ED395');
        $this->addSql('ALTER TABLE software DROP FOREIGN KEY FK_77D068CFADF66B1A');
        $this->addSql('ALTER TABLE software DROP FOREIGN KEY FK_77D068CF2D234F6A');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25ADF66B1A');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25A76ED395');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25896DBBDE');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F52652E6E');
        $this->addSql('ALTER TABLE tom DROP FOREIGN KEY FK_7DDF7313A76ED395');
        $this->addSql('ALTER TABLE tom DROP FOREIGN KEY FK_7DDF73132D234F6A');
        $this->addSql('ALTER TABLE vorfall DROP FOREIGN KEY FK_B270345FA76ED395');
        $this->addSql('ALTER TABLE vorfall DROP FOREIGN KEY FK_B270345F2D234F6A');
        $this->addSql('ALTER TABLE vorfall DROP FOREIGN KEY FK_B270345FADF66B1A');
        $this->addSql('ALTER TABLE vvt DROP FOREIGN KEY FK_8130A6A5A76ED395');
        $this->addSql('ALTER TABLE vvt DROP FOREIGN KEY FK_8130A6A58C6D2968');
        $this->addSql('ALTER TABLE vvt DROP FOREIGN KEY FK_8130A6A5ADF66B1A');
        $this->addSql('ALTER TABLE vvt DROP FOREIGN KEY FK_8130A6A52D234F6A');
        $this->addSql('ALTER TABLE vvtdsfa DROP FOREIGN KEY FK_281CB90EA76ED395');
        $this->addSql('ALTER TABLE vvtdsfa DROP FOREIGN KEY FK_281CB90EADF66B1A');
        $this->addSql('ALTER TABLE datenweitergabe DROP FOREIGN KEY FK_4D6337B7C4062E7F');
        $this->addSql('ALTER TABLE policies DROP FOREIGN KEY FK_E08BBFCE2DE62210');
        $this->addSql('ALTER TABLE policies_vvt DROP FOREIGN KEY FK_ECB63CBFE4479645');
        $this->addSql('ALTER TABLE policies_vvtpersonen DROP FOREIGN KEY FK_3A4A1837E4479645');
        $this->addSql('ALTER TABLE policies_vvtdatenkategorie DROP FOREIGN KEY FK_1FEC288EE4479645');
        $this->addSql('ALTER TABLE forms_produkte DROP FOREIGN KEY FK_43DCA781F5AB0B87');
        $this->addSql('ALTER TABLE vvt_produkte DROP FOREIGN KEY FK_D823B054F5AB0B87');
        $this->addSql('ALTER TABLE software DROP FOREIGN KEY FK_77D068CF2DE62210');
        $this->addSql('ALTER TABLE software_vvt DROP FOREIGN KEY FK_EBE8FA17D7452741');
        $this->addSql('ALTER TABLE software_datenweitergabe DROP FOREIGN KEY FK_22997BA8D7452741');
        $this->addSql('ALTER TABLE software_config DROP FOREIGN KEY FK_8C564DD6D7452741');
        $this->addSql('ALTER TABLE akademie_kurse_team DROP FOREIGN KEY FK_5A1E4998296CD8AE');
        $this->addSql('ALTER TABLE audit_tom DROP FOREIGN KEY FK_401DB23296CD8AE');
        $this->addSql('ALTER TABLE audit_tom_abteilung DROP FOREIGN KEY FK_A7C0EB17296CD8AE');
        $this->addSql('ALTER TABLE audit_tom_ziele DROP FOREIGN KEY FK_C37215B8296CD8AE');
        $this->addSql('ALTER TABLE client_request DROP FOREIGN KEY FK_69AACBE2296CD8AE');
        $this->addSql('ALTER TABLE datenweitergabe DROP FOREIGN KEY FK_4D6337B7296CD8AE');
        $this->addSql('ALTER TABLE forms DROP FOREIGN KEY FK_FD3F1BF7296CD8AE');
        $this->addSql('ALTER TABLE fos_user DROP FOREIGN KEY FK_957A6479296CD8AE');
        $this->addSql('ALTER TABLE fos_user DROP FOREIGN KEY FK_957A64799E73AC3E');
        $this->addSql('ALTER TABLE fos_user DROP FOREIGN KEY FK_957A64796352511C');
        $this->addSql('ALTER TABLE kontakte DROP FOREIGN KEY FK_1A62EA2F296CD8AE');
        $this->addSql('ALTER TABLE policies DROP FOREIGN KEY FK_E08BBFCE296CD8AE');
        $this->addSql('ALTER TABLE produkte DROP FOREIGN KEY FK_497DBEB3296CD8AE');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784296CD8AE');
        $this->addSql('ALTER TABLE software DROP FOREIGN KEY FK_77D068CF296CD8AE');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25296CD8AE');
        $this->addSql('ALTER TABLE tom DROP FOREIGN KEY FK_7DDF7313296CD8AE');
        $this->addSql('ALTER TABLE vorfall DROP FOREIGN KEY FK_B270345F296CD8AE');
        $this->addSql('ALTER TABLE vvt DROP FOREIGN KEY FK_8130A6A5296CD8AE');
        $this->addSql('ALTER TABLE vvtdatenkategorie DROP FOREIGN KEY FK_91E13AAD296CD8AE');
        $this->addSql('ALTER TABLE vvtgrundlage DROP FOREIGN KEY FK_407DE499296CD8AE');
        $this->addSql('ALTER TABLE vvtpersonen DROP FOREIGN KEY FK_35C2589F296CD8AE');
        $this->addSql('ALTER TABLE vvtrisiken DROP FOREIGN KEY FK_E92CF2E6296CD8AE');
        $this->addSql('ALTER TABLE tom DROP FOREIGN KEY FK_7DDF73132DE62210');
        $this->addSql('ALTER TABLE vvt DROP FOREIGN KEY FK_8130A6A5147295F6');
        $this->addSql('ALTER TABLE vorfall DROP FOREIGN KEY FK_B270345F2DE62210');
        $this->addSql('ALTER TABLE vorfall_vvtpersonen DROP FOREIGN KEY FK_2DF87A01EA8E2EC4');
        $this->addSql('ALTER TABLE vorfall_vvtdatenkategorie DROP FOREIGN KEY FK_802FDBF7EA8E2EC4');
        $this->addSql('ALTER TABLE policies_vvt DROP FOREIGN KEY FK_ECB63CBF677671F9');
        $this->addSql('ALTER TABLE software_vvt DROP FOREIGN KEY FK_EBE8FA17677671F9');
        $this->addSql('ALTER TABLE vvt DROP FOREIGN KEY FK_8130A6A52DE62210');
        $this->addSql('ALTER TABLE vvt_vvtgrundlage DROP FOREIGN KEY FK_A27B631A677671F9');
        $this->addSql('ALTER TABLE vvt_vvtpersonen DROP FOREIGN KEY FK_8B3FCF56677671F9');
        $this->addSql('ALTER TABLE vvt_vvtdatenkategorie DROP FOREIGN KEY FK_7FEC93B1677671F9');
        $this->addSql('ALTER TABLE vvt_vvtrisiken DROP FOREIGN KEY FK_1FAB2B94677671F9');
        $this->addSql('ALTER TABLE vvt_datenweitergabe DROP FOREIGN KEY FK_33B13935677671F9');
        $this->addSql('ALTER TABLE vvt_produkte DROP FOREIGN KEY FK_D823B054677671F9');
        $this->addSql('ALTER TABLE vvtdsfa DROP FOREIGN KEY FK_281CB90E677671F9');
        $this->addSql('ALTER TABLE policies_vvtdatenkategorie DROP FOREIGN KEY FK_1FEC288E45450705');
        $this->addSql('ALTER TABLE vorfall_vvtdatenkategorie DROP FOREIGN KEY FK_802FDBF745450705');
        $this->addSql('ALTER TABLE vvt_vvtdatenkategorie DROP FOREIGN KEY FK_7FEC93B145450705');
        $this->addSql('ALTER TABLE vvtdsfa DROP FOREIGN KEY FK_281CB90E2DE62210');
        $this->addSql('ALTER TABLE vvt_vvtgrundlage DROP FOREIGN KEY FK_A27B631A80257D66');
        $this->addSql('ALTER TABLE policies_vvtpersonen DROP FOREIGN KEY FK_3A4A183797064E08');
        $this->addSql('ALTER TABLE vorfall_vvtpersonen DROP FOREIGN KEY FK_2DF87A0197064E08');
        $this->addSql('ALTER TABLE vvt_vvtpersonen DROP FOREIGN KEY FK_8B3FCF5697064E08');
        $this->addSql('ALTER TABLE vvt_vvtrisiken DROP FOREIGN KEY FK_1FAB2B94DF7C8617');
        $this->addSql('ALTER TABLE vvt DROP FOREIGN KEY FK_8130A6A56BF700BD');
        $this->addSql('DROP TABLE akademie_buchungen');
        $this->addSql('DROP TABLE akademie_kurse');
        $this->addSql('DROP TABLE akademie_kurse_team');
        $this->addSql('DROP TABLE audit_tom');
        $this->addSql('DROP TABLE audit_tom_audit_tom_ziele');
        $this->addSql('DROP TABLE audit_tom_audit_tom_abteilung');
        $this->addSql('DROP TABLE audit_tom_abteilung');
        $this->addSql('DROP TABLE audit_tom_status');
        $this->addSql('DROP TABLE audit_tom_ziele');
        $this->addSql('DROP TABLE client_comment');
        $this->addSql('DROP TABLE client_request');
        $this->addSql('DROP TABLE datenweitergabe');
        $this->addSql('DROP TABLE datenweitergabe_grundlagen');
        $this->addSql('DROP TABLE datenweitergabe_stand');
        $this->addSql('DROP TABLE forms');
        $this->addSql('DROP TABLE forms_produkte');
        $this->addSql('DROP TABLE forms_audit_tom_abteilung');
        $this->addSql('DROP TABLE fos_user');
        $this->addSql('DROP TABLE kontakte');
        $this->addSql('DROP TABLE policies');
        $this->addSql('DROP TABLE policies_vvt');
        $this->addSql('DROP TABLE policies_vvtpersonen');
        $this->addSql('DROP TABLE policies_vvtdatenkategorie');
        $this->addSql('DROP TABLE produkte');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE software');
        $this->addSql('DROP TABLE software_vvt');
        $this->addSql('DROP TABLE software_datenweitergabe');
        $this->addSql('DROP TABLE software_config');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE tom');
        $this->addSql('DROP TABLE upload');
        $this->addSql('DROP TABLE vorfall');
        $this->addSql('DROP TABLE vorfall_vvtpersonen');
        $this->addSql('DROP TABLE vorfall_vvtdatenkategorie');
        $this->addSql('DROP TABLE vvt');
        $this->addSql('DROP TABLE vvt_vvtgrundlage');
        $this->addSql('DROP TABLE vvt_vvtpersonen');
        $this->addSql('DROP TABLE vvt_vvtdatenkategorie');
        $this->addSql('DROP TABLE vvt_vvtrisiken');
        $this->addSql('DROP TABLE vvt_datenweitergabe');
        $this->addSql('DROP TABLE vvt_produkte');
        $this->addSql('DROP TABLE vvtdatenkategorie');
        $this->addSql('DROP TABLE vvtdsfa');
        $this->addSql('DROP TABLE vvtgrundlage');
        $this->addSql('DROP TABLE vvtpersonen');
        $this->addSql('DROP TABLE vvtrisiken');
        $this->addSql('DROP TABLE vvtstatus');
    }
}
