name: Run Development Build and Tests
env:
  GITHUB_TOKEN: ${{ secrets.token }}

on:
  push:
    branches:
      - development
      - feature/docker*

jobs:
  artifact:
    uses: ./.github/workflows/task-artifact.yml

  create_release:
    needs:
      - artifact
    runs-on: ubuntu-latest
    outputs:
      create_release_output: ${{ steps.version.outputs.version }}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v5.0.2
        id: version
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          change_path: .
          version_format: "${major}.${minor}.${patch}-${increment}"

      - uses: actions/download-artifact@v4
        with:
          name: artifact_${{github.run_number}}

      - run: unzip -qq artifact_${{github.run_number}}.zip -d artifact

      - name: Set laF_version in .env
        run: |
          sed -i 's/^laF_version=.*/laF_version=${{ steps.version.outputs.version }}/' .env

      - name: Archive Release for application
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'application.zip'
          exclusions: '*.git* *.github* /*node_modules/* /*var/* .editorconfig'
          directory: artifact

      - name: Create new Release with semantic-version tag
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          prerelease: true
          name: DEV Release ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          artifacts: artifact/application.zip
          artifactContentType: application/zip
          bodyFile: RELEASE_NOTE.md

  docker:
    needs:
      - create_release
    uses: ./.github/workflows/task-docker.yml
    with:
      reponame: 'git.h2-invent.com/datenschutzcenter/application'
      version: ${{ needs.create_release.outputs.create_release_output }}
      dockerfile_path: './Dockerfile'
      directory: '.'
      tags: 'git.h2-invent.com/datenschutzcenter/application:development,git.h2-invent.com/datenschutzcenter/application:${{ needs.create_release.outputs.create_release_output }}'
    secrets:
      docker_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
