name: Run Development Build and Tests
env:
  GITHUB_TOKEN: ${{ secrets.token }}

on:
  push:
    branches:
      - development
      - feature/docker*

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v5.0.2
        id: version
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          change_path: .
          version_format: "${major}.${minor}.${patch}-${increment}"

  artifact:
    uses: ./.github/workflows/task-artifact.yml

  prerelease:
    needs:
      - artifact
      - version
    uses: ./.github/workflows/task-release.yml
    with:
      version: ${{ needs.version.outputs.version }}
      prerelease: true

  docker:
    needs:
      - version
    uses: ./.github/workflows/task-docker.yml
    with:
      reponame: 'git.h2-invent.com/datenschutzcenter/application'
      version: ${{ needs.version.outputs.version }}
      dockerfile_path: './Dockerfile'
      directory: '.'
      tags: 'git.h2-invent.com/datenschutzcenter/application:${{ needs.version.outputs.version }},git.h2-invent.com/datenschutzcenter/application:development'
    secrets:
      docker_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      docker_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
