name: Code Analysis

on: workflow_call

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --prefer-dist

      - name: Run script
        run: vendor/bin/phpstan analyse
