name: "Run TODO to Issue"

on: [ "push" ]

jobs:
  create_issues:
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
    steps:
      - name: Checkout Repository
        uses: "actions/checkout@v4"

      - name: "TODO to Issue"
        uses: alstr/todo-to-issue-action@v5
